version: '3'
services:
  mysql:
    image: si_mysql:latest
    container_name: si_mysql_1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - /var/lib/docker/smap/mysql_statuses/mysql_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 'TISA.2022'
      MYSQL_DATABASE: 'polin'
      MYSQL_USER: 'si'
      MYSQL_PASSWORD: 'tisapolines'
  adminer:
    image: si_adminer:latest
    container_name : si_adminer_1
    restart: always
    ports:
      - 8080:8080
  python:
    image: si_mysql_injectStatus:latest
    container_name : si_mysql_injectStatus_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/local"
    command : "python3 /root/main.py"
    restart: always